apiVersion: v1
kind: Secret
metadata:
    name: hashproof-secret
    namespace: dev
data:
    DB_USERNAME: ENC[AES256_GCM,data:r+GBE6EWXRI=,iv:faU3YausbyJ6SC/vvVipYAzNYZS++r5BuEuVar/nnNE=,tag:aaTDVbEaUbiaYQZYKqVJUg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:GqVIBzdK/vmS7Cg7vsSH6A==,iv:U6fH3qg0pmaOLHG9epDeg2db49AJlB0JmPNUVVNDuyc=,tag:cu6rsiNGW4dpGQM2lP0JDg==,type:str]
    HEDERA_OPERATOR_ID: ENC[AES256_GCM,data:GynTgA3zn74=,iv:TSzX69TX5QwtZflkUDoRhebxiQTOYmkW4sXo30TexzE=,tag:dwEUlSXxxe38fiJLnlE6FQ==,type:str]
    HEDERA_OPERATOR_KEY: ENC[AES256_GCM,data:VVNE3mtkIVew9nHIC7p5u4p4vJu3MCxsHEcVgTwWYaMHEi+sfn8im7wB+sw36J6jw278uhgLSrMl16la306mmAWvBuPlE9+Q6MXKn9QNzf5NmdpBYWMpNhR+pqbGHF2p,iv:1JcOdyY3Y3OoasxWzJvZll5unz8LAOfpLt/hXYzi95A=,tag:9Y8aHe1W84N9oAKKS2Jv0w==,type:str]
    HEDERA_TOPIC_ID: ENC[AES256_GCM,data:yPWv7n7ziP53,iv:fcln7lHrHBrPk3y8MTQJsLT7zYVZFz1F5257ld45Tz8=,tag:VL5EcPHAN03d69d0wOn6gQ==,type:str]
    SECRET: ENC[AES256_GCM,data:lxrddg4EOBQTp1kfF60XYQ==,iv:Qki1MghlHfhWkLrEAn38IokD8pbnHQ4/86ifzZ7GbyQ=,tag:sDyWoUkbrwJKnzXJOWTGwQ==,type:str]
    access_token_secret_key: ENC[AES256_GCM,data:elJQKdCNSR26oBF23uFYNjF+cJDYl373i0kvPmpaHTalMZqnrZZvATRliLo=,iv:YAE6yjgMP4RBu1lGEgD5s1d8CZDs7duvo2NlXfiqPvQ=,tag:Z4ZZdY1V52cgcohEQ60MXQ==,type:str]
    refresh_token_secret_key: ENC[AES256_GCM,data:apYN/6uS6CCLDQWxL/VfJBSThyqKEhm2nDDRdACq4qAjAhpMluIKX8gT+WCZ,iv:fZR+OM+E3y+rXjm0VfaQbkvygdyVo11D1Vb6vDSU6pU=,tag:8qxAIA+1QZJr1Okr+ahMUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-27T09:25:54Z"
    mac: ENC[AES256_GCM,data:cfOvkPxcKjJw0+RYGFzJ7VappmG8MK3ZimXGI1niiznOAUgZN1PC30TSbP4J98cUbQ80i2ork/30JbAzv2wkX5Ya9Ue1z3+GXw7nL50Hdd0r9PLYglNuJE8MjNPFhrFmpKtu2AW3u3uFZcVv22WrAP40O4vGplAO5suORpc5Wiw=,iv:+Pti1M763nOVfTBWD0ECZsmGYW/evQc9KIchr0iBPC4=,tag:Gs3QjlqM61G3pNGegWJIRg==,type:str]
    pgp:
        - created_at: "2024-02-27T09:25:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5pHROLxzew7AQv/TrS2IuXyiX5txHZ8+10lIv3ZM8JcHDgaLJz3qwGnZz47
            N2xw45jDV/wPZ94/JxnF0+smuC1CORTF2BwROAKJFYbAOK97/+qvGCUgpj0wA0kq
            wIJkscVHWz5Y9yedt01c1qzCgtoeFC4/nMNUPnwMhcYi6gAxV/akLT9i+l6Kt+nB
            ZfT0xsSaIH/gOEu1AGNsPvoBFmwejxc/5DYOkv0tBdtcRQR3PAQvoXzFv/EV8e1t
            E7SxBdh+whFglhBtysfnz3pDVRjVCr0h2odZN5x/Vv4WScuuTzEH7ViSDEukQr1K
            icqaPtXZ8fUUWhny+ZNUEVSpEV6nia8rDJ/Q9D/m05Hy2QL86dnDIJA5F8QyUb07
            OS5gYTsq3GTNoCXtqhwNfUBK61AwkJO7OIUw44PomYhVmvIb03KhdF9w8Tq+/tID
            jimfnhrInNK/F+QZHXo5shkXDisQ4P7roDeRuHaBAnvEOPXWeULuMNRYbrCv8ygg
            aNZl+mHwg+AxKYI62N8+1GYBCQIQVWuo/jhnz/Z9OEXcULcxW19UJcJvnSQyrPKo
            0c+iy+dSmdC6mmnJ8QPOt+1U7WcOAxhJNjHnOnEqEe/lIkqWoJHxAvXDdsSbq+38
            /lSwJEvm7GKFKicQfgB1agSaUJRn4WE=
            =ZmLP
            -----END PGP MESSAGE-----
          fp: 6DECC8DC828B9B66A5DA858DAF001BF5752D163A
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
