apiVersion: v1
kind: Secret
metadata:
    name: hashproof-service-test
    namespace: dev
data:
    TEST: ENC[AES256_GCM,data:rYI9VA==,iv:sOHy/Qyip6ES7acsCCfIDs4FjUd9LDizZy4PzzWC1mA=,tag:/mej/eZvNdrKNnfhwqwyiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-26T21:32:22Z"
    mac: ENC[AES256_GCM,data:2nWMYRuaK14IflZmpdI4Dd1kixLjrOOB8awRuvzT2+gh4fQyvBR32RLcjedTRctnkafVb5MFatdmx0YR606h6QxgrJPpz8l+kiY/yOnYz1qcZB6E2vrucsyq0p4Hyfd+D9vPLE4fU2zW1BA47PhxDfUnKW9xOONtgHUtG2Llutc=,iv:4YKUb+Z/TX2d9/WsSndXvpzg6DbUOkOrRBx8rKt2SOw=,tag:SC2i3+O+4Cer3mTI+5g0Nw==,type:str]
    pgp:
        - created_at: "2024-02-26T21:32:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5pHROLxzew7AQv+Oh313ZmkeT72Cb2FaFi4M6veKo+cki0GLUQq4z/5NHEG
            JBuDxoPDHxiO4QfqlAIPugk6Ehp2HnnCp/+M/QQeoZKWdJj3AFY049EgWCCN/7w8
            Y7a+je+zIBdRf78I7VHmSiYlw+tPkNP0t3vXIlOsLpbB5soOvyjWvWQZyt7oJ0FE
            TxCrVVOw69cdWWWjPogX1UjUkG1FKwW570J4ot1I2NM5r/4ThBkwBlpN7XmrNbEk
            2CMqVEZa5qfOAukpxgrMUsRVgYhV5TIxrW0TINfVVdkAXJo1jTdFs9Faag7IuSwx
            bvd9gVVbYLH3vai4kjeSJCvDJmG3Uqu3HB5eP9r0QMiINsFrUzDKyHd8FZpBnSve
            Kj1S8MhKWIQoE78/+TEjnE6hRxR1xdWytYnhknTNAsVAAffp53t+Pw2Kmx43H5LG
            9eUpET1t3ht8S9n7dHkT5+xCADEXTNv8leUUg45fkLEF2xKeIjgwnjJR1qsLZzSf
            Uj50hHxRNflyXPuxuG/t1GYBCQIQy4Z6o5frPY3P6Nnc3lHuoj/ofj2P3KHgvxoU
            B+r3wGjIXEIREXl0sy8K9zfsonZxTbubPxjPgkM6BJAVijFif0+7If32q/NzHYZc
            KQI12GEaczSy/JNgygRFoeLwo34J5WM=
            =kZYc
            -----END PGP MESSAGE-----
          fp: 6DECC8DC828B9B66A5DA858DAF001BF5752D163A
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
