apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: hashproof-service-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.enc.yaml
