apiVersion: v1
kind: Secret
metadata:
    name: hashproof-secret
    namespace: dev
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:Jn67YhyG+aA=,iv:BArMiczMPK9JXK6Lmkot3wkO/WCwFExABBtkNdwqejA=,tag:l5zF2x4c78eHpxN960NUxg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:h4eqZEUgoMO2uNUFpSqjyg==,iv:a1K2EOmOan3vTtlF/5sS+qAAHZDuECOxV38HW3lIpm4=,tag:b/n/Tra4yQZID9S5sKYcFg==,type:str]
    HEDERA_OPERATOR_ID: ENC[AES256_GCM,data:yc0/C/crcDs=,iv:qe7rCTVQ9xLKnVTcAw8xhpvKnExOIZNXpEjJ/iR2q1c=,tag:lYHiXNpjcaW/jCjYkHoizw==,type:str]
    HEDERA_OPERATOR_KEY: ENC[AES256_GCM,data:xuYySvIk+b9n9wPEZ5xfUNjSiQo8c6pRCPJmbex4fCw2K4R2JGpE+CenOACc3wNdIjJ6d9zY1GzaUedmVhDnzOgNakjKA3umw/7FgVZqZ1YMKSXZRd1EIO5+KhBFDizh,iv:RgUMgamswTHjwnuK1p8crtw0zMatDDjsW0irEm9gTkI=,tag:sBarE8ZI8iA0cU7vVRLIow==,type:str]
    HEDERA_TOPIC_ID: ENC[AES256_GCM,data:/40fBkk9TacO,iv:0S1+TOn1a8xkcTkcGel0zgy7Ca0e9MfbMMciXqIj46M=,tag:fYX7FTxWgj5kp7hzQZpu5w==,type:str]
    SECRET: ENC[AES256_GCM,data:7v1NS2efHCv8mQH46YmvXg==,iv:jSur5D44xMMM8sMoZ/ObXPXbF8Nphh14pWZrdAK7Kl4=,tag:/Dd/q4eOJWAkuypVqnne0A==,type:str]
    access_token_secret_key: ENC[AES256_GCM,data:OvJyHx+Szv35nXJIAQryE4BMGC3uAbviWwLIZqCHV+ei+2Nwgqle9DDBYIo=,iv:rzVFgZRxPo6pYxJPZfHvzLhl+lKW8V87+Hgqu3rUZlU=,tag:60pkYaAl+1xP/NycQRPg4w==,type:str]
    refresh_token_secret_key: ENC[AES256_GCM,data:fb1cG+ee8VbfR5F58lJy2f6gI2EVYhMfInMKKE2+Coftw3gCwa7lL9lfDLyX,iv:DLMDzGDAPwsB4YTW/K/K3mTws3GL+w+i3TwhJysLyqE=,tag:CgQUew1fxhXytoqMBy2NrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-27T10:19:01Z"
    mac: ENC[AES256_GCM,data:VgCGc3Ro+gX+h2nxin8IFqF/lQB+TdnfmQiHdRZagXNpIYzGaCdbK8cGf31uNhxID0z9AR7HQi7FXMKw/ewg7kYJFkWmZ1uXI6UjpLDTRzhEBjLTVGxtz5DZmQwOKWeCLG3TU6Z4NUzryfXp5WibzJVg/lqUq/UVv33kHgcGnx0=,iv:IT/JqSfPS0dxXL6kcOmiq8z01HUKAyJjNMBgLhJnl7I=,tag:4yflKPjeKYLExp/KR32e0g==,type:str]
    pgp:
        - created_at: "2024-02-27T10:19:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAwSi8XwPOimnAQv/UqOVcaWEy1+iU/ioHXX/yaBssVHIQWXi/KXBRJkKpOce
            j5H4ktIMvcqqBcYQWAtOriFeBMvOcgCBGCeeluBA9ff+W0UmFEmJ7aj1oscYRHsE
            XT4lb748iFHNlEN05WuBRjfo2vw5DjbeO5NIHLk2+BPyHPIApPVz1ukP7aHVRFEv
            G+G6D9YMqwlcvvRoBdbzlalA5wUBWrcWMzAyQqJo46beE8y+5e18yi2kT3pWj3yP
            r4PYdfGCTFe4ciZp0cI9PA7ZEROgaLZfgJK4ZrySwdf9H7FtY/KYm0QwfhZVDUL1
            5GEASxkbZp17x5Jo8hoiEJCKKWPzLU20+i3W3jU9ixra29AA3YduNTzg22LDxcdW
            8YPsr9rsYpR2xB2JWatFHq6VG6yP49n3gJCLCRh5WAMhWRsIs2tlOB6EtEwn2xWi
            rTqEvCJs9GCtlTF5RiIRGLhbvdnrlEzkwAgJh5EFGs8jiFlsF06dziAqN0bKe8oW
            h5FkjpajSnsC4N8XmFmG1GgBCQIQ/HCrVH56C1hnBovO/GEtuYP7RGXjvw0hhKrM
            Q6n6ZxDqeqNle2AbaT6yL0e1l1ERhc3UXCEJwQDVr1Nmq0p4P387S28z1mYTmj8D
            QpmBZK1xoBBAgDla/8P+IBkZYC8ppKOTfw==
            =oRME
            -----END PGP MESSAGE-----
          fp: 2E3D8770D116DF858C40D590402C6942652AF5FF
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
