{{- $values := .Values -}}
{{ range .Values.apps }}
{{ if not .disabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $values.targetNamespace}}-{{ .name }}
  namespace: cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $values.spec.destination.project }}
  source:
    repoURL: {{ $values.spec.source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ $values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - {{ .source.valueFile }}
  destination:
    server: {{ $values.spec.destination.server }}
    namespace: {{ $values.targetNamespace }}
  {{ if .autoSync -}}
  syncPolicy:
    automated: {}
  {{ else -}}
  syncPolicy: {}
  {{ end }}
{{ end }}
{{ end }}
