{{ if eq .Values.spec.destination.project "dev" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashproof-dev-secrets
  namespace: dev
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: environment/secrets/dev
    repoURL: https://github.com/OleksandrKorliuk/hashproof-platform.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
