replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: us-central1-docker.pkg.dev/proofofaction/hashproof-repo/hedera-hashproof-consumer
  tag: 0.0.3
  pullPolicy: Always
  ports:
    name: http
    protocol: TCP
    containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  path: /
  hosts:
    - domain.com
  tls: true
  secretName: hashproof-consumer-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

config:
  DATABASE_URL: jdbc:postgresql://10.242.160.3:5432/hedera_hashproof
  HIKARI_CONN_TIMEOUT: 3000
  HIKARI_IDLE_TIME_OUT: 60000
  HIKARI_MAX_POOL_SIZE: 10
  HIKARI_MIN_IDLE: 5
  HEDERA_ENVIRONMENT: TESTNET
  PULSAR_URL: pulsar://pulsar-r1-proxy.pulsar:6650
  PULSAR_HASPROOF_TOPIC_NAME: hashproof-hcs-topic
  PULSAR_HASHPROOF_CONSUMER_NAME: hash-proof-event-consumer
  PULSAR_HASHPROOF_SUBSCRIPTION_NAME: hashproof-event-subscription
  PULSAR_DEAD_LETTER_HASHPROOF_TOPIC_NAME: dead-letter-hp-topic
  MESSAGE_REDELIVERY_DELAY: 2

  MESSAGE_RETRY_COUNT: 6

secrets:
  name: hashproof-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
