replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ""
  tag: ""
  pullPolicy: Always
  ports:
    name: http
    protocol: TCP
    containerPort: 8000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

config: {}

secrets: {}

backup:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
