replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: us-central1-docker.pkg.dev/proofofaction/hashproof-repo/hedera-hashproof-consumer
  tag: 0.1.1
  pullPolicy: Always
  ports:
    name: http
    protocol: TCP
    containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  path: /
  hosts:
    - domain.com
  tls: true
  secretName: hashproof-consumer-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

config:
  SERVER_PORT: 8080
  HEDERA_ENVIRONMENT: TESTNET
  MIRROR_NODE_ADDRESS: testnet.mirrornode.hedera.com:443
  DATABASE_URL: jdbc:postgresql://10.242.160.3:5432/hedera_hashproof
  HIKARI_CONN_TIMEOUT: 3000
  HIKARI_IDLE_TIME_OUT: 60000
  HIKARI_MAX_POOL_SIZE: 10
  HIKARI_MIN_IDLE: 5
  PULSAR_URL: pulsar://pulsar-r1-proxy.pulsar:6650
  PULSAR_HASHPROOF_DEADLETTER_TOPIC_NAME: hashproof-hcs-topic-dl
  PULSAR_HASHPROOF_SUBSCRIPTION_NAME: hashproof-tx-sub
  PULSAR_HASPROOF_TOPIC_NAME: hashproof-hcs-topic-new
  PULSAR_HASHPROOF_CONSUMER_NAME: hashproof-tx-consumer
  PULSAR_MAX_REDELIVER_COUNT: 5
  RECEIPT_POOL_SIZE: 40
  RECEIPT_EXECUTOR_THREADS: 8
  RECEIPT_EXECUTOR_QUEUE_SIZE: 100
  RECEIPT_EXECUTOR_DELAY: 15s
  LOGGING_ROOT_LVL: warn
  LOGGING_HASHPROOF_LVL: info

secrets:
  name: hashproof-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
