replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/proofofaction/hashproof-repo/hedera-hashproof-service
  tag: 0.0.3
  ports:
    name: http
    protocol: TCP
    containerPort: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  tls: true
  secretName: hashproof-service-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - domain.com

config:
  SERVER_PORT: 8080
  MAX_FILE_SIZE: 5mb
  DATABASE_URL: jdbc:postgresql://10.242.160.3:5432/hedera_hashproof
  HIKARI_CONN_TIMEOUT: 3000
  HIKARI_IDLE_TIMEOUT: 60000
  HIKARI_MAX_POOL_SIZE: 50
  HIKARI_MIN_IDLE: 20
  DDL_AUTO: create

  HEDERA_ENVIRONMENT: TESTNET
  MIRROR_NODE_URL: https://testnet.mirrornode.hedera.com
  MIRROR_NODE_ADDRESS: hcs.testnet.mirrornode.hedera.com:5600
  MIRROR_NODE_API_VERSION: /api/v1/
  MIRROR_NODE_TOPIC_BASE_URI: /api/v1/topics/
  MIRROR_NODE_TRANSACTION_BASE_URI: /api/v1/transactions/

  PULSAR_URL: pulsar://pulsar-r1-proxy.pulsar:6650
  PULSAR_HASPROOF_TOPIC_NAME: hashproof-hcs-topic
  PULSAR_HASHPROOF_PRODUCER_NAME: hashproof-hcs

secrets:
  name: hashproof-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
