replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/proofofaction/hashproof-repo/hedera-hashproof-service
  tag: 0.1.4
  ports:
    name: http
    protocol: TCP
    containerPort: 8080

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  tls: true
  secretName: hashproof-service-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - domain.com

config:
  SERVER_PORT: 8080
  PROFILES_ACTIVE: oauth
  MAX_FILE_SIZE: 5MB
  HEDERA_ENVIRONMENT: TESTNET
  MIRROR_NODE_ADDRESS: testnet.mirrornode.hedera.com:443
  DATABASE_URL: jdbc:postgresql://10.242.160.3:5432/hedera_hashproof
  HIKARI_CONN_TIMEOUT: 3000
  HIKARI_IDLE_TIMEOUT: 60000
  HIKARI_MAX_POOL_SIZE: 20
  HIKARI_MIN_IDLE: 10
  DDL_AUTO: validate
  PULSAR_ADMIN_URL: pulsar://pulsar-r1-proxy.pulsar:8080
  PULSAR_URL: pulsar://pulsar-r1-proxy.pulsar:6650
  PULSAR_HASPROOF_TOPIC_NAME: hashproof-hcs-topic-new
  PULSAR_HASHPROOF_PRODUCER_NAME: hashproof-hcs
  LOGGING_ROOT_LVL: warn
  LOGGING_HASHPROOF_LVL: info

secrets:
  name: hashproof-secret

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
