{{- $fullName := include "hashproof-consumer.name" . -}}
{{- $chartVersion := include "hashproof-consumer.chart" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    helm.sh/chart: {{ $chartVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value :=  .Values.config }}
    {{ $key }}: {{ $value | quote}}
    {{- end }}

