{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hashproof-consumer.name" . -}}
{{- $chartVersion := include "hashproof-consumer.chart" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    helm.sh/chart: {{ $chartVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .Values.ingress.secretName }}
    {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - path: {{ $ingressPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                name: http
  {{- end }}
  {{- end }}
